// “Can you do these without looking?” items, one list per lesson (shared with the readiness page).
export const CHECKS: Record<string, string[]> = {
  learning: [
    "Explain the difference between regression and classification, and supervised and unsupervised learning, with an example of each.",
    "Explain why having labels makes it easier to define and compare learning methods.",
    "Write the design matrix for a small dataset, including the ones column, and state the shapes of X, θ, y.",
    "Interpret a fitted coefficient correctly (holding other features fixed) and say why the intercept may be meaningless.",
  ],
  loss: [
    "Define a residual and say which sign means under-prediction.",
    "Explain why the plain sum of residuals is a useless objective.",
    "Write SSE in summation and matrix form; relate SSE, RSS and MSE.",
    "Explain why argmin SSE = argmin MSE but the minimum values differ.",
    "Explain the mechanism by which a single outlier moves the least-squares line.",
  ],
  stats: [
    "Contrast probability and statistics, and explain why larger samples do not fix systematic bias.",
    "Define an unbiased estimator and classify the sample mean, variance, std. deviation, median and range.",
    "Derive E[s²] = σ² and explain the N − 1.",
    "Compute covariance and correlation for a small dataset and interpret their signs.",
    "Give a counterexample showing r = 0 does not mean “no relationship”.",
  ],
  ols1d: [
    "Derive both normal equations for ŷ = θ₀ + θ₁x without notes.",
    "Explain each step that turns the slope equation into S_xy/S_xx.",
    "Fit a line to 3–5 points by hand using deviations and verify it with Σe = 0 and Σxe = 0.",
    "Explain what translating or centring x does to the slope and intercept.",
    "State when the solution fails to be unique.",
  ],
  matrix: [
    "Expand (y − Xθ)ᵀ(y − Xθ) and justify combining the cross terms.",
    "Derive the gradient and the normal equations; state the full-rank condition.",
    "Prove the stationary point is a global minimum using vᵀHv = 2‖Xv‖².",
    "Explain the projection picture and connect Xᵀe = 0 to the residual identities.",
    "Recognise rank-deficient designs (duplicate, constant, or too many columns).",
  ],
  gd: [
    "Derive the single-example gradient and the LMS update rule.",
    "Write batch GD in summation and matrix form, with the correct factor 2/m.",
    "Perform one batch and one SGD update by hand, using the old θ for every component.",
    "Explain what too-small and too-large learning rates do, and why centring helps.",
    "Compare batch GD and SGD: cost per update, behaviour near the minimum.",
  ],
  mle: [
    "State the probabilistic model and the conditional distribution of yⱼ given 𝐱ⱼ.",
    "Write the likelihood and explain why it is a product.",
    "Derive the log-likelihood and show its maximiser is the OLS solution.",
    "Explain why σ² does not affect θ̂, and why the likelihood is not a distribution over θ.",
    "Say which assumption is used at each step of the derivation.",
  ],
  assumptions: [
    "State each of the four assumptions precisely, conditional on x.",
    "Recognise each violation from a residual plot.",
    "Explain the difference between errors and residuals.",
    "Explain why skewed y overall, or non-normal x, does not by itself violate the assumptions.",
  ],
  features: [
    "Explain “linear in the parameters” and give one linear and one nonlinear-regression example.",
    "Write the design matrix for a polynomial model of degree d.",
    "Explain why training SSE cannot increase as nested features are added.",
    "Interpret an indicator coefficient and an interaction term, including the gap at a given input.",
  ],
  regularisation: [
    "Write the ridge objective and derive its closed-form solution, stating the intercept convention.",
    "Compute a one-feature ridge slope S_xy/(S_xx + λ) and explain why training SSE rises.",
    "Convert λ between the SSE and MSE conventions.",
    "Explain geometrically why LASSO gives sparse solutions and ridge does not.",
    "Explain why features must be scaled before penalising and how λ should be chosen.",
  ],
  evaluation: [
    "State what training, validation and test data are each allowed to influence.",
    "Distinguish parameters from hyperparameters and describe grid search.",
    "Compute RMSE, MAE, R² and adjusted R² from residuals, and interpret each.",
    "Explain why test R² can be negative and why training R² cannot (OLS with intercept).",
    "Describe forward selection and backward elimination, and why greedy search can fail.",
  ],
  knn: [
    "Compute 1-NN, k-NN and local-linear predictions for a small 1-D dataset by hand.",
    "Explain how k affects the prediction curve, training error and bias/variance.",
    "Explain why feature scaling changes k-NN predictions.",
    "Contrast parametric and non-parametric models, including prediction cost.",
  ],
  biasvar: [
    "Define bias and variance at a fixed input, over repeated training sets.",
    "Derive the three-term decomposition and say where each assumption is used.",
    "Explain why the noise term is absent when error is measured against f(x).",
    "Compute bias, variance and expected error for simple discrete prediction distributions.",
    "Relate degree, λ and k to bias and variance, and explain how to find the balance in practice.",
  ],
};
