import { M, MB } from '../../components/Math';
import { Callout, Checklist, Lab, Quiz, Sec, Steps, Table, TryThis } from '../../components/ui';
import { BaseRateLab } from '../../interactives/week3/BaseRateLab';
import { CHECKS3 } from './checks';

export default function L04BaseRate() {
  return (
    <>
      <Sec title="Translate the words first">
        <p>
          A lab test returns a correct positive result in 98% of cases where the disease is present, and a correct negative in 97% of cases where
          it is absent; 0.8% of the population has the disease. A patient tests positive. Do they have it?
        </p>
        <p>
          Let <M t="C" /> mean the condition is present and <M t="+" /> a positive result. Before any arithmetic, translate each phrase into a probability:
        </p>
        <MB t="P(C) = 0.008, \quad P(\neg C) = 0.992, \quad P(+ \mid C) = 0.98, \quad P(+ \mid \neg C) = 1 - 0.97 = 0.03." />
        <p>
          “Correct negative in 97%” is <M t="P(- \mid \neg C)" />, so the false-positive rate is its complement. The question asks for{' '}
          <M t="P(C \mid +)" /> — the reverse conditional.
        </p>
      </Sec>

      <Sec title="Work through every class">
        <Steps
          steps={[
            {
              title: 'Score each hypothesis: likelihood × prior',
              body: <MB t="s_C = 0.98 \times 0.008 = 0.00784, \qquad s_{\neg C} = 0.03 \times 0.992 = 0.02976." />,
            },
            {
              title: 'MAP decision',
              body: (
                <p>
                  <M t="0.02976 > 0.00784" />, so <M t="h_{\text{MAP}} = \neg C" /> — “not cancer”, despite the positive test.
                </p>
              ),
            },
            {
              title: 'Normalise for the probability',
              body: (
                <>
                  <MB t="P(C \mid +) = \frac{0.00784}{0.00784 + 0.02976} = \frac{49}{235} \approx 0.2085, \qquad P(\neg C \mid +) \approx 0.7915." />
                  <p>The denominator sums over all mutually exclusive hypotheses, so the posteriors add to 1.</p>
                </>
              ),
            },
          ]}
        />
        <Callout kind="example" title="Check with natural frequencies">
          Imagine 100,000 people generated by this model (expected counts):
          <Table
            head={['true status', 'positive', 'negative', 'total']}
            rows={[
              ['condition present', '784', '16', '800'],
              ['condition absent', '2,976', '96,224', '99,200'],
              ['total', '3,760', '96,240', '100,000'],
            ]}
          />
          Of the 3,760 positive results, only 784 have the condition: <M t="784/3760 = 0.2085" />. The denominator is{' '}
          <em>all ways to obtain a positive result</em> — not all people with the condition. The small false-positive rate applies to a huge group.
        </Callout>
        <Lab title="Base rates as people" purpose="Each square is one person. Change the prevalence and the test quality and watch who ends up with a positive result.">
          <BaseRateLab />
        </Lab>
        <TryThis
          items={[
            'At the default numbers, count the dark squares: about 8 true positives against about 30 false alarms.',
            'Raise specificity to 0.999. False alarms almost vanish and P(C | +) jumps — for a rare condition, specificity matters more than sensitivity.',
            'Raise the prevalence to 0.2 (a symptomatic patient rather than a random screen). The same test now gives a high posterior.',
            'Set “positive tests in a row” to 2. If the tests are independent given the true status, the likelihood ratio is squared.',
          ]}
        />
      </Sec>

      <Sec title="The evidence still mattered">
        <p>
          The posterior is below ½, but the positive result raised the probability from 0.8% to about 20.9% — a 26-fold increase. “Below 50%” does not mean
          “the evidence had no effect”. Whether 21% should trigger action is a question about the <em>costs</em> of the two kinds of mistake — the next
          lesson.
        </p>
        <Callout kind="note" title="A reusable method">
          Name the events; translate each conditional; compute likelihood × prior for every class; sum to normalise; then state the decision rule. Do not
          pick a label before knowing which error costs the question uses.
        </Callout>
      </Sec>

      <Sec title="Check your understanding">
        <Quiz
          id="w3.l4.q1"
          q={<p>Why is 0.98 not the answer to P(C | +)?</p>}
          options={[
            { text: 'Because 0.98 is the probability of a positive among people with the condition — a different denominator.', correct: true, why: 'P(+|C) conditions on C; P(C|+) conditions on the positive result.' },
            { text: 'Because the test is not 100% accurate.', why: 'Even a 99.9%-sensitive test has P(C|+) depending on prevalence and specificity.' },
          ]}
        />
        <Quiz
          id="w3.l4.q2"
          q={<p>Prevalence 0.1, P(+ | C) = 0.9, P(+ | ¬C) = 0.1. What is P(C | +)?</p>}
          options={[
            { text: '0.9', why: 'That is the sensitivity.' },
            { text: '0.5', correct: true, why: 'Scores 0.09 and 0.09: equal, so the posterior is exactly ½.' },
            { text: '0.1', why: 'That is the prior; the positive result changes it.' },
          ]}
        />
        <Quiz
          id="w3.l4.q3"
          q={<p>“The posterior is only 0.21, so the positive result told us nothing.” Evaluate.</p>}
          options={[
            { text: 'True — below 0.5 means no evidence.', why: 'The probability rose from 0.008 to 0.21.' },
            { text: 'False: the evidence multiplied the odds by the likelihood ratio 0.98/0.03 ≈ 32.7; it just started from a very low prior.', correct: true, why: 'Evidence changes beliefs; the decision also depends on the prior and the costs.' },
          ]}
        />
      </Sec>

      <Callout kind="key">
        A posterior combines the test’s behaviour with the base rate. For a rare condition, the many false positives from the large healthy group can
        outnumber the true positives, so <M t="P(C \mid +)" /> can be small even for an accurate test. Compute the score for every class, normalise, and
        check with natural frequencies.
      </Callout>

      <Checklist id="w3-baserate" items={CHECKS3['w3-baserate']} />
    </>
  );
}
