// Week 2 “Can you do these without looking?” items, one list per lesson (shared with the readiness page).
export const CHECKS2: Record<string, string[]> = {
  'w2-classifier': [
    'Distinguish a score, a class probability and a predicted label, and say what turns one into the next.',
    'Explain the difference between discriminative and generative learning, naming what each one models.',
    'Use Bayes’ rule to turn class-conditional likelihoods and priors into a posterior, and explain why p(x) can be ignored when comparing classes.',
    'Give an example where comparing likelihoods alone (ignoring priors) predicts the wrong class.',
  ],
  'w2-centroid': [
    'Explain why the weight vector w is perpendicular to the boundary xᵀw = t.',
    'Derive w = p − n and t = (‖p‖² − ‖n‖²)/2 for the basic linear classifier.',
    'Prove the boundary is the set of points equidistant (Euclidean) from the two class means.',
    'Classify a query with the score and verify the answer with squared distances.',
    'Explain what goes wrong when the class means coincide or a class is multimodal.',
  ],
  'w2-sigmoid': [
    'Explain why linear regression on 0/1 labels does not give valid probabilities.',
    'Write the logistic model, compute σ(z) for a few scores, and interpret h_β(x) as P(Y = 1 | x).',
    'Show that σ(z) ≥ 0.5 ⇔ z ≥ 0, so the decision boundary is linear in the features.',
    'Convert a probability threshold τ into a score threshold log(τ/(1 − τ)) and the boundary in x.',
    'Explain what scaling all coefficients does to the probabilities and to the 0.5 boundary.',
  ],
  'w2-logloss': [
    'Write the Bernoulli probability p^y (1 − p)^(1−y) and check both cases.',
    'Derive the log-likelihood and the average negative log-likelihood (log loss) from it.',
    'State exactly where independence and the binary labels are used.',
    'Compute the loss of a single observation and explain why confident mistakes cost so much.',
    'Explain why the squared loss of a sigmoid output is not the objective used here.',
  ],
  'w2-logfit': [
    'Derive σ′(z) = σ(z)(1 − σ(z)) and the per-example score derivative p − y.',
    'Write the gradient (1/m) Xᵀ(p − y) and perform one simultaneous gradient-descent update by hand.',
    'Explain why there is no OLS-style closed form for logistic regression.',
    'Explain what convexity guarantees and give a case (separable data, duplicate columns) where a unique finite minimiser fails to exist.',
  ],
  'w2-cv': [
    'State the three assumptions behind generalisation from a sample.',
    'Distinguish what training, validation and test data are each allowed to influence.',
    'Describe holdout, K-fold CV and LOOCV, with training size per fit and number of fits.',
    'Select a hyperparameter from fold error counts, weighting by fold size when folds differ.',
    'Explain why preprocessing must be fitted inside each training fold, and why a best CV score is optimistic.',
  ],
  'w2-datatypes': [
    'Classify features as nominal, binary, ordinal, count, time, interval or irrelevant.',
    'Explain why arbitrary integer codes invent distances between categories.',
    'Explain why order does not imply equal gaps, and why cyclic time needs special treatment.',
    'Describe a simple matching distance for nominal features.',
  ],
  'w2-metrics': [
    'Draw a labelled confusion matrix (rows actual, columns predicted) and define TP, FP, FN, TN.',
    'Compute accuracy, error, precision, recall and F1, and name the population each denominator counts.',
    'Explain why high accuracy can hide a useless classifier when positives are rare.',
    'Derive F1 = 2TP/(2TP + FP + FN) from the harmonic mean and say why it ignores TN.',
    'Recognise when precision or recall is undefined.',
  ],
  'w2-roc': [
    'Explain how lowering the threshold changes TP, FP, recall and precision.',
    'Define TPR and FPR, and explain why FPR is not 1 − precision.',
    'Construct an ROC curve from a small list of scores and labels, handling ties, and compute its AUC.',
    'Interpret AUC = 1 and AUC = 0.5, and explain what AUC does not tell you.',
  ],
  'w2-missing': [
    'Explain why a missing value is not a zero, and list common causes of missingness.',
    'Compare deletion, mean/median/mode imputation, a missing category, predictive imputation and model support.',
    'Show with numbers why mean imputation shrinks the variance of a column.',
    'Explain how deleting rows can bias a sample, and why imputation must be fitted on training data only.',
  ],
  'w2-distance': [
    'Write the Minkowski distance and specialise it to Manhattan, Euclidean and Chebyshev distance.',
    'Compute d₁, d₂, d∞ and the mismatch count for a pair of vectors.',
    'Sketch the unit “circles” for p = 1, 2, ∞ and explain what each prefers.',
    'Explain why squared Euclidean distance ranks neighbours exactly as Euclidean distance does.',
  ],
  'w2-metric': [
    'State the four metric properties (zero at self, positive otherwise, symmetry, triangle inequality).',
    'Use a counterexample to show Minkowski p = ½ violates the triangle inequality.',
    'Show squared Euclidean distance is not a metric.',
    'Define a pseudometric and give the zero-weight example.',
  ],
  'w2-exemplar': [
    'Prove the mean uniquely minimises the sum of squared Euclidean distances.',
    'Distinguish centroid, geometric median and medoid by their objective and allowed centres.',
    'Find a medoid by evaluating every candidate, and state the cost.',
    'Describe the nearest-centroid classifier and give a multimodal counterexample.',
  ],
  'w2-knn': [
    'Write the k-NN vote with the indicator function and trace it on a small dataset.',
    'Explain why 1-NN and 3-NN can disagree on the same query.',
    'Contrast k-NN classification (vote) with k-NN regression (mean) and interpret the fraction of positive neighbours.',
    'Explain which ties odd k removes and which it does not.',
  ],
  'w2-scaling': [
    'Explain how a feature measured in large units can dominate Euclidean distance.',
    'Apply min-max and z-score normalisation using training statistics.',
    'Explain why a test value outside [0, 1] after min-max scaling is not an error.',
    'Explain why scaling fixes units but not relevance.',
  ],
  'w2-weighted': [
    'Explain how k affects bias, variance and the shape of the decision regions.',
    'Say what unweighted k-NN predicts at k = m, and why distance-weighted k-NN does not become constant.',
    'Compute an inverse-square-weighted vote and a weighted-average regression prediction.',
    'Handle zero distances and avoid squaring an already-squared distance.',
  ],
  'w2-lazyeval': [
    'Explain why 1-NN self-match training error is zero and what that does (not) tell you.',
    'Compute 1-NN leave-one-out error for a small dataset.',
    'State the storage and brute-force query cost of k-NN, and the cost of LOOCV.',
    'Explain why k cannot exceed the training size inside each LOOCV fit.',
  ],
  'w2-curse': [
    'Explain the exponential growth of grid cells with dimension.',
    'Explain how irrelevant features swamp relevant ones in a distance.',
    'Describe distance concentration: nearest and farthest become relatively similar.',
    'Describe remedies: feature selection, attribute weights chosen by validation, larger k, editing instances (IB3).',
  ],
};
